apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: recipe-api
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com
    targetRevision: HEAD
    path: https://github.com/jph-23/recipe-gitops.git

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
